# Generated by Django 4.2.16 on 2024-10-24 14:00

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=30)),
                ('suffix', models.CharField(choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('None', 'None')], default='None', max_length=5)),
                ('LRN', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('last_login', models.DateTimeField()),
                ('last_logout', models.DateTimeField()),
                ('face_img', models.ImageField(blank=True, null=True, upload_to=api.models.student_directory_path)),
            ],
        ),
    ]
