# Generated by Django 5.1.2 on 2024-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FingerprintImageModel',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fingerprints',
            new_name='fingerprint1',
        ),
        migrations.AddField(
            model_name='student',
            name='fingerprint2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
