# Generated by Django 5.1.2 on 2024-10-18 08:48

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_fingerprintimagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprint1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.student_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprint2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.student_directory_path),
        ),
    ]
